sudo: false
language: python
python:
 - "2.7"
 - "3.2"
 - "3.3"
 - "3.4"
 - "3.5"
 - "3.6"
 - "3.7-dev"
env:
  matrix:
   - DJANGO="Django<1.9"
   - DJANGO="Django<1.10"
   - DJANGO="Django<1.11"
   - DJANGO="Django<1.12"
   - DJANGO="Django<2.1"
   - DJANGO="Django<2.2"
cache:
  directories:
    - $HOME/.cache/pip
install:
 # pip >=8 dropped Python 3.2 support
 - pip install "pip<8.0.0" wheel
 - pip install "$DJANGO" "coverage==3.7.1" coveralls "mock>=1.0.1"
 - pip install .
 - pip install flake8
 - pip install -r requirements.txt
matrix:
  exclude:
    # Supported Django/Python versions - https://docs.djangoproject.com/en/1.11/faq/install/#what-python-version-can-i-use-with-django
    # Latest Django 1.8
    - python: "3.2"
      env: DJANGO="Django<1.9"
    - python: "3.6"
      env: DJANGO="Django<1.9"
    - python: "3.7-dev"
      env: DJANGO="Django<1.9"
    # Latest Django 1.9
    - python: "3.2"
      env: DJANGO="Django<1.10"
    - python: "3.3"
      env: DJANGO="Django<1.10"
    - python: "3.6"
      env: DJANGO="Django<1.10"
    - python: "3.7-dev"
      env: DJANGO="Django<1.10"
    # Latest Django 1.10
    - python: "3.2"
      env: DJANGO="Django<1.11"
    - python: "3.3"
      env: DJANGO="Django<1.11"
    - python: "3.6"
      env: DJANGO="Django<1.11"
    - python: "3.7-dev"
      env: DJANGO="Django<1.11"
    # Latest Django 1.11
    - python: "3.2"
      env: DJANGO="Django<1.12"
    - python: "3.3"
      env: DJANGO="Django<1.12"
    - python: "3.7-dev"
      env: DJANGO="Django<1.12"
    # Latest Django 2.0
    - python: "2.7"
      env: DJANGO="Django<2.1"
    - python: "3.2"
      env: DJANGO="Django<2.1"
    - python: "3.3"
      env: DJANGO="Django<2.1"
    - python: "3.7-dev"
      env: DJANGO="Django<2.1"
    # Latest Django 2.1
    - python: "2.7"
      env: DJANGO="Django<2.2"
    - python: "3.2"
      env: DJANGO="Django<2.2"
    - python: "3.3"
      env: DJANGO="Django<2.2"
    - python: "3.4"
      env: DJANGO="Django<2.2"
  allow_failures:
    - python: 3.7-dev
branches:
 only:
  - master
  - dev
script:
  # - flake8 --exclude=migrations health_monitor
  - coverage run manage.py test
after_success:
  - bash <(curl -s https://codecov.io/bash)
