sudo: false
language: python
python:
 - "2.7"
 - "3.2"
 - "3.3"
 - "3.4"
 - "3.5"
env:
  matrix:
   - DJANGO="Django<1.8"
   - DJANGO="Django<1.9"
   - DJANGO="Django<1.10"
   - DJANGO="Django<1.11"
cache:
  directories:
    - $HOME/.cache/pip
install:
 # pip >=8 dropped Python 3.2 support
 - pip install "pip<8.0.0" wheel
 - pip install "$DJANGO"
 - pip install .
matrix:
  exclude:
    - python: "3.5"
      env: DJANGO="Django<1.8"
    # Django 1.9+ no longer supports python 3.2/3.3
    - python: "3.2"
      env: DJANGO="Django<1.10"
    - python: "3.3"
      env: DJANGO="Django<1.10"
    - python: "3.2"
      env: DJANGO="Django<1.11"
    - python: "3.3"
      env: DJANGO="Django<1.11"
branches:
 only:
  - master
script:
  # - flake8 --exclude=migrations health_monitor
  - python manage.py test
after_success:
  # - bash <(curl -s https://codecov.io/bash)
