# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-24 01:52
from __future__ import unicode_literals

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Health',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField(db_index=True, unique=True, verbose_name=b'UID')),
                ('state', jsonfield.fields.JSONField(blank=True, default={}, null=True)),
                ('severity', jsonfield.fields.JSONField(blank=True, default={}, null=True)),
                ('change_date', models.DateTimeField(blank=True, default=None, null=True)),
            ],
        ),
    ]
